version: "3.7"

services:

  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: bookmarks_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarks
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "0.0.0.0:5432:5432"